# API Configuration
api:
  # Main API Service
  main:
    host: "0.0.0.0"
    port: 8000
    workers: 4
    
  # Literature Mining API
  literature_mining:
    host: "0.0.0.0"
    port: 8001
    workers: 2
    
  # Machine Learning API
  ml_engine:
    host: "0.0.0.0"
    port: 8002
    workers: 2
    
  # Frontend API
  frontend:
    host: "0.0.0.0"
    port: 3000

# CORS Configuration
cors:
  origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
  methods:
    - GET
    - POST
    - PUT
    - DELETE
  headers:
    - Content-Type
    - Authorization

# Authentication Configuration
auth:
  secret_key: ${SECRET_KEY}
  algorithm: "HS256"
  access_token_expire_minutes: 30
  refresh_token_expire_days: 7
